import { createContext } from "react";

export const LANGUAGE_STORAGE_KEY = "smartevent-language";

export const translations = {
  en: {
    navHome: "Home",
    navWishlist: "Wishlist",
    navBookings: "Bookings",
    navTickets: "Tickets",
    navReferrals: "Referrals",
    navProfile: "Profile",
    navNotifications: "Notifications",
    navUnread: "unread",
    navClose: "Close",
    navNoNotifications: "No notifications yet",
    navViewAllNotifications: "View all notifications",
    navAdminPanel: "Admin Panel",
    navOrganizerDashboard: "Organizer Dashboard",
    navGreeting: "Hi",
    navLogout: "Logout",
    languageLabel: "Language",
    languageEnglish: "English",
    languageHindi: "Hindi",
    lightMode: "Light",
    darkMode: "Dark",
    switchToLightMode: "Switch to light mode",
    switchToDarkMode: "Switch to dark mode",
    loadingEventDetails: "Loading event details...",
    date: "Date",
    time: "Time",
    category: "Category",
    location: "Location",
    tickets: "Tickets",
    ticketAvailable: "ticket available",
    ticketsAvailable: "tickets available",
    soldOutNotice: "Tickets are sold out for this event.",
    shareEvent: "Share event",
    inviteYourCircle: "Invite your circle",
    whatsapp: "WhatsApp",
    copyLink: "Copy link",
    eventLinkCopied: "Event link copied.",
    copyFailed: "Copy failed. Please copy the URL from your browser.",
    shareEventText: "Check out {title} on SmartEvent: {url}",
    eventCancelled: "Event Cancelled",
    expired: "Expired",
    soldOut: "Sold Out",
    available: "Available",
    quantity: "Qty",
    subtotal: "Subtotal",
    discount: "Discount",
    payNow: "Pay now",
    couponPlaceholder: "Coupon code",
    apply: "Apply",
    bookNow: "Book Now",
    enterCouponFirst: "Enter a coupon code first.",
    ticketsSoldOut: "Tickets are sold out.",
    invalidCoupon: "Invalid coupon",
    unavailableForBooking: "This event is no longer available for booking.",
    validTicketQuantity: "Please enter a valid ticket quantity.",
    onlyTicketsAvailable: "Only {count} ticket(s) available.",
    paymentFailed: "Payment failed",
    aboutEvent: "About the event",
    liveUpdates: "Live Updates",
    announcements: "Announcements",
    update: "update",
    updates: "updates",
    noAnnouncements: "No live announcements have been posted yet.",
    importantAnnouncement: "Important Announcement",
    eventUpdate: "Event Update",
    ratingsAndReviews: "Ratings and reviews",
    reviewsFrom: "{rating} / 5 from {count} reviews",
    reviewPlaceholder: "Share your experience after attending this event...",
    submitReview: "Submit Review",
    reviewSubmitted: "Review submitted successfully.",
    reviewSubmitFailed: "Unable to submit review.",
    noWrittenReview: "No written review.",
    delete: "Delete",
    login: "Login",
    enterEmail: "Enter Email",
    enterPassword: "Enter Password",
    referralCodeOptional: "Referral code (optional)",
    invalidEmailOrPassword: "Invalid email or password",
    createNewAccount: "Create New Account",
    forgotPassword: "Forgot Password?",
    adminLogin: "Admin Login",
    register: "Register",
    enterUsername: "Enter Username",
    registeredSuccessfully: "Registered successfully",
    registrationFailed: "Registration failed",
    alreadyHaveAccount: "Already have an account? Login",
    forgotPasswordTitle: "Forgot Password",
    confirmEmail: "Confirm Email",
    emailsDoNotMatch: "Emails do not match",
    resetInstructionsSent: "Password reset instructions sent to your email.",
    resetRequestFailed: "Reset request failed",
    clickHereToReset: "Click Here to Reset",
    resetPassword: "Reset Password",
    enterNewPassword: "Enter New Password",
    confirmNewPassword: "Confirm New Password",
    passwordResetSuccessful: "Password reset successful. Redirecting to login...",
    passwordResetFailed: "Password reset failed",
    discoverLiveExperiences: "Discover live experiences",
    heroTitle: "Find events worth showing up for.",
    heroSubtitle: "Search by category, location, date, price, and what people are booking most.",
    searchEvents: "Search events...",
    allCategories: "All Categories",
    sortDateAsc: "Date ↑",
    sortDateDesc: "Date ↓",
    popularity: "Popularity",
    priceLow: "Price Low",
    priceHigh: "Price High",
    search: "Search",
    clear: "Clear",
    all: "All",
    active: "Active",
    cancelled: "Cancelled",
    recommendedForYou: "Recommended for You",
    picks: "picks",
    trendingEvents: "Trending Events",
    popularNow: "Popular now",
    noEventsFound: "No events found",
    tryChangingFilters: "Try changing filters",
    removeFromWishlist: "Remove {title} from wishlist",
    saveToWishlist: "Save {title} to wishlist",
    saveEvent: "Save event",
    viewDetails: "View Details",
    onwards: "onwards",
    chatbotLabel: "SmartEvent chatbot",
    chatbotAssistant: "SmartEvent Assistant",
    chatbotSubtitle: "Event discovery and support",
    chatbotInitialMessage: "Hi, I am your SmartEvent assistant. Ask me to find events, show bookings, or help with tickets.",
    chatbotTrending: "Trending events",
    chatbotBookings: "My bookings",
    chatbotMusic: "Suggest music events this weekend",
    chatbotTickets: "Help with ticket issues",
    chatbotUnavailable: "I could not reach the assistant right now. Please try again.",
    openRelatedPage: "Open related page",
    thinking: "Thinking...",
    askEventsTickets: "Ask about events or tickets...",
    send: "Send",
    openAssistant: "Open SmartEvent assistant",
    loading: "Loading...",
    myBookings: "My Bookings",
    bookingsSubtitle: "Review your tickets, payment totals, and booking status.",
    noBookingsYet: "No bookings yet",
    bookingsEmptyHelp: "Once a booking is created, it will appear here with status details.",
    bookingNumber: "Booking #{id}",
    eventId: "Event ID",
    finalPaid: "Final Paid",
    myTickets: "My Tickets",
    ticketsSubtitle: "View confirmed ticket details and QR pass in a clean card layout.",
    eventTicket: "Event Ticket",
    bookingId: "Booking ID",
    eventDate: "Event Date",
    totalPaid: "Total Paid",
    ticketCode: "Ticket Code",
    qrCode: "QR Code",
    ticketCancelledInvalid: "Event cancelled. QR code is no longer valid.",
    ticketExpiredInvalid: "Ticket expired. QR code is no longer valid.",
    downloadTicket: "Download Ticket",
    myWishlist: "My Wishlist",
    wishlistSubtitle: "Save events now and jump back into booking whenever you are ready.",
    noSavedEvents: "No saved events yet",
    wishlistEmptyHelp: "Tap the heart on an event card to keep it here for later.",
    remove: "Remove",
    notificationsSubtitle: "Booking, payment, event, and system updates in one place.",
    markAllRead: "Mark all as read",
    read: "Read",
    unread: "Unread",
    markAsRead: "Mark as Read",
    paymentCancelled: "Payment was cancelled. You can try again.",
    checkoutLoadFailed: "Unable to load checkout details.",
    paymentFailedRetry: "Payment failed. Please try again.",
    paymentCouldNotProcess: "Payment could not be processed.",
    paymentSessionMissing: "Payment session is missing. Please start checkout again.",
    stripeNotConfigured: "Stripe is not configured. Use simulated checkout.",
    stripeOpenFailed: "Unable to open Stripe checkout.",
    loadingCheckout: "Loading checkout...",
    secureCheckout: "Secure checkout",
    completePayment: "Complete your payment",
    bookingTotal: "Booking total",
    payableAmount: "Payable amount",
    paymentStatus: "Payment status",
    processing: "Processing...",
    payWithStripe: "Pay with Stripe",
    payWithTestCard: "Pay with Test Card",
    simulateFailure: "Simulate Failure",
    backToBookings: "Back to bookings",
    paymentFailedTitle: "Payment Failed",
    paymentSuccessful: "Payment Successful",
    paymentFailureCopy: "Your payment could not be completed. Please retry checkout.",
    paymentSuccessCopy: "Your booking is confirmed and your ticket is being prepared.",
    transactionReference: "Transaction reference",
    amount: "Amount",
    viewMyTickets: "View My Tickets",
    myProfile: "My Profile",
    profileSubtitle: "Manage your account details and view booking activity.",
    smartEventUser: "SmartEvent User",
    editProfile: "Edit Profile",
    username: "Username",
    email: "Email",
    saving: "Saving...",
    saveProfile: "Save Profile",
    profileUpdated: "Profile updated successfully.",
    profileUpdateFailed: "Unable to update profile.",
    activitySummary: "Activity Summary",
    totalBookings: "Total Bookings",
    upcomingEvents: "Upcoming Events",
    ticketsBooked: "Tickets Booked",
    totalSpent: "Total Spent",
    pending: "Pending",
    closedEvents: "Closed Events",
    rewardPoints: "Reward Points",
    rewardPointsHelp: "+10 per confirmed booking, +5 per review",
    referralSystem: "Referral System",
    referralSubtitle: "Invite friends to SmartEvent and earn reward points when they join.",
    yourReferralCode: "Your Referral Code",
    referralCode: "Referral Code",
    successfulReferrals: "Successful Referrals",
    referralPoints: "Referral Points",
    referralHelp: "Earn +{points} reward points for each successful referral.",
    copyReferralCode: "Copy Code",
    shareReferralCode: "Share Code",
    referralCopied: "Referral code copied.",
    referralShareCopied: "Referral message copied.",
    referralCopyFailed: "Unable to copy referral code.",
    referralLoadFailed: "Unable to load referral details.",
    referralShareText: "Join me on SmartEvent. Use my referral code: {code}",
    referralPointsValue: "{points} points from referrals",
    totalEvents: "Total Events",
    activeEvents: "Active Events",
    totalTicketsSold: "Total Tickets Sold",
    totalRevenue: "Total Revenue",
    ongoingEvents: "Ongoing Events",
    completedEvents: "Completed Events",
    cancelledEvents: "Cancelled Events",
    adminOrganizerLogin: "Admin / Organizer Login",
    enterAdminEmail: "Enter Admin Email",
    enterAdminPassword: "Enter Admin Password",
    loginAsAdmin: "Login as Admin",
    adminOrganizerRequired: "Admin/Organizer access required",
    adminLoginFailed: "Admin login failed",
    platformAnalytics: "Platform Analytics",
    analyticsSubtitle: "Admin dashboard for SmartEvent insights",
    dashboard: "Dashboard",
    users: "Users",
    events: "Events",
    bookings: "Bookings",
    loadingAnalytics: "Loading analytics...",
    analyticsLoadFailed: "Failed to load analytics.",
    dailyTicketSales: "Daily Ticket Sales",
    topRevenueEvents: "Top Revenue Events",
    popularEvents: "Popular Events",
    monthlyBookingTrends: "Monthly Booking Trends",
    bookingTrendCopy: "Booking trend data is available in daily sales view.",
    last7DaysAverage: "Last 7 days average",
    bestPerformingDay: "Best performing day",
    usersOverview: "Users Overview",
    usersOverviewSubtitle: "Manage registered users and account roles.",
    loadingUsers: "Loading users...",
    usersLoadFailed: "Unable to load users.",
    registeredUsers: "Registered Users",
    id: "ID",
    role: "Role",
    noUsersFound: "No users found.",
    eventsOverview: "Events Overview",
    eventsOverviewSubtitle: "Browse platform events and lifecycle status.",
    loadingEvents: "Loading events...",
    eventsLoadFailed: "Unable to load events.",
    allEvents: "All Events",
    title: "Title",
    status: "Status",
    organizerId: "Organizer ID",
    price: "Price",
    bookingOverview: "Booking Overview",
    bookingOverviewSubtitle: "Review booking activity across the platform.",
    loadingBookings: "Loading bookings...",
    bookingsLoadFailed: "Unable to load bookings.",
    allBookings: "All Bookings",
    userId: "User ID",
    revenue: "Revenue",
    noBookingsFound: "No bookings found.",
    adminDashboard: "Admin Dashboard",
    organizerDashboard: "Organizer Dashboard",
    admin: "Admin",
    organizer: "Organizer",
    platformAnalyticsLink: "Platform Analytics",
    eventInsights: "Event Insights",
    closeInsights: "Close Insights",
    loadingInsights: "Loading insights...",
    insightsLoadFailed: "Failed to load event insights",
    ticketsSold: "Tickets Sold",
    remainingTickets: "Remaining Tickets",
    bookingCount: "Booking Count",
    salesProgress: "Sales Progress",
    ticketsSoldProgress: "{sold} / {total} tickets sold",
    addEvent: "Add Event",
    updateEvent: "Update Event",
    cancelEdit: "Cancel Edit",
    description: "Description",
    selectCategory: "Select Category",
    comedy: "Comedy",
    music: "Music",
    tech: "Tech",
    business: "Business",
    sports: "Sports",
    workshop: "Workshop",
    selectedImagePreview: "Selected image preview:",
    selectedEventBannerPreview: "Selected event banner preview",
    fillAllEventFields: "Please fill in all event fields, including the event image.",
    eventUpdated: "Event updated",
    eventAdded: "Event added",
    eventAddFailed: "Failed to add event",
    eventCancelledNotify: "Event cancelled & users notified",
    cancelFailed: "Cancel failed",
    enterAnnouncementFirst: "Enter an announcement message first",
    eventUpdatePosted: "Event update posted",
    eventUpdatePostFailed: "Failed to post event update",
    yourEvents: "Your Events",
    thumbnail: "thumbnail",
    viewInsights: "View Insights",
    edit: "Edit",
    cancelEvent: "Cancel Event",
    postLiveUpdate: "Post a live update for attendees...",
    important: "Important",
    postUpdate: "Post Update",
    statusConfirmed: "CONFIRMED",
    statusCancelled: "CANCELLED",
    statusExpired: "EXPIRED",
    statusPending: "PENDING",
  },
  hi: {
    navHome: "होम",
    navWishlist: "विशलिस्ट",
    navBookings: "बुकिंग्स",
    navTickets: "टिकट",
    navReferrals: "रेफरल",
    navProfile: "प्रोफाइल",
    navNotifications: "सूचनाएं",
    navUnread: "अनपढ़",
    navClose: "बंद करें",
    navNoNotifications: "अभी कोई सूचना नहीं",
    navViewAllNotifications: "सभी सूचनाएं देखें",
    navAdminPanel: "एडमिन पैनल",
    navOrganizerDashboard: "ऑर्गनाइजर डैशबोर्ड",
    navGreeting: "नमस्ते",
    navLogout: "लॉगआउट",
    languageLabel: "भाषा",
    languageEnglish: "अंग्रेजी",
    languageHindi: "हिंदी",
    lightMode: "लाइट",
    darkMode: "डार्क",
    switchToLightMode: "लाइट मोड पर जाएं",
    switchToDarkMode: "डार्क मोड पर जाएं",
    loadingEventDetails: "इवेंट विवरण लोड हो रहा है...",
    date: "तारीख",
    time: "समय",
    category: "श्रेणी",
    location: "स्थान",
    tickets: "टिकट",
    ticketAvailable: "टिकट उपलब्ध",
    ticketsAvailable: "टिकट उपलब्ध",
    soldOutNotice: "इस इवेंट के टिकट बिक चुके हैं.",
    shareEvent: "इवेंट शेयर करें",
    inviteYourCircle: "अपने लोगों को आमंत्रित करें",
    whatsapp: "व्हाट्सऐप",
    copyLink: "लिंक कॉपी करें",
    eventLinkCopied: "इवेंट लिंक कॉपी हो गया.",
    copyFailed: "कॉपी नहीं हो सका. कृपया ब्राउजर से URL कॉपी करें.",
    shareEventText: "SmartEvent पर {title} देखें: {url}",
    eventCancelled: "इवेंट रद्द",
    expired: "समाप्त",
    soldOut: "बिक चुका",
    available: "उपलब्ध",
    quantity: "मात्रा",
    subtotal: "सबटोटल",
    discount: "छूट",
    payNow: "अभी भुगतान करें",
    couponPlaceholder: "कूपन कोड",
    apply: "लागू करें",
    bookNow: "अभी बुक करें",
    enterCouponFirst: "पहले कूपन कोड दर्ज करें.",
    ticketsSoldOut: "टिकट बिक चुके हैं.",
    invalidCoupon: "अमान्य कूपन",
    unavailableForBooking: "यह इवेंट अब बुकिंग के लिए उपलब्ध नहीं है.",
    validTicketQuantity: "कृपया टिकट की सही मात्रा दर्ज करें.",
    onlyTicketsAvailable: "केवल {count} टिकट उपलब्ध हैं.",
    paymentFailed: "भुगतान विफल रहा",
    aboutEvent: "इवेंट के बारे में",
    liveUpdates: "लाइव अपडेट्स",
    announcements: "घोषणाएं",
    update: "अपडेट",
    updates: "अपडेट्स",
    noAnnouncements: "अभी तक कोई लाइव घोषणा पोस्ट नहीं हुई है.",
    importantAnnouncement: "महत्वपूर्ण घोषणा",
    eventUpdate: "इवेंट अपडेट",
    ratingsAndReviews: "रेटिंग और रिव्यू",
    reviewsFrom: "{rating} / 5, {count} रिव्यू",
    reviewPlaceholder: "इवेंट में शामिल होने के बाद अपना अनुभव साझा करें...",
    submitReview: "रिव्यू सबमिट करें",
    reviewSubmitted: "रिव्यू सफलतापूर्वक सबमिट हुआ.",
    reviewSubmitFailed: "रिव्यू सबमिट नहीं हो सका.",
    noWrittenReview: "लिखित रिव्यू नहीं है.",
    delete: "हटाएं",
    login: "लॉगिन",
    enterEmail: "ईमेल दर्ज करें",
    enterPassword: "पासवर्ड दर्ज करें",
    referralCodeOptional: "रेफरल कोड (वैकल्पिक)",
    invalidEmailOrPassword: "ईमेल या पासवर्ड अमान्य है",
    createNewAccount: "नया अकाउंट बनाएं",
    forgotPassword: "पासवर्ड भूल गए?",
    adminLogin: "एडमिन लॉगिन",
    register: "रजिस्टर",
    enterUsername: "यूजरनेम दर्ज करें",
    registeredSuccessfully: "रजिस्ट्रेशन सफल हुआ",
    registrationFailed: "रजिस्ट्रेशन विफल रहा",
    alreadyHaveAccount: "पहले से अकाउंट है? लॉगिन करें",
    forgotPasswordTitle: "पासवर्ड भूल गए",
    confirmEmail: "ईमेल कन्फर्म करें",
    emailsDoNotMatch: "ईमेल मेल नहीं खाते",
    resetInstructionsSent: "पासवर्ड रीसेट निर्देश आपके ईमेल पर भेजे गए.",
    resetRequestFailed: "रीसेट अनुरोध विफल रहा",
    clickHereToReset: "रीसेट करने के लिए क्लिक करें",
    resetPassword: "पासवर्ड रीसेट करें",
    enterNewPassword: "नया पासवर्ड दर्ज करें",
    confirmNewPassword: "नया पासवर्ड कन्फर्म करें",
    passwordResetSuccessful: "पासवर्ड रीसेट सफल. लॉगिन पर भेजा जा रहा है...",
    passwordResetFailed: "पासवर्ड रीसेट विफल रहा",
    discoverLiveExperiences: "लाइव अनुभव खोजें",
    heroTitle: "ऐसे इवेंट खोजें जहां जाना बनता है.",
    heroSubtitle: "श्रेणी, स्थान, तारीख, कीमत और लोकप्रिय बुकिंग के आधार पर खोजें.",
    searchEvents: "इवेंट खोजें...",
    allCategories: "सभी श्रेणियां",
    sortDateAsc: "तारीख ↑",
    sortDateDesc: "तारीख ↓",
    popularity: "लोकप्रियता",
    priceLow: "कम कीमत",
    priceHigh: "अधिक कीमत",
    search: "खोजें",
    clear: "साफ करें",
    all: "सभी",
    active: "सक्रिय",
    cancelled: "रद्द",
    recommendedForYou: "आपके लिए सुझाए गए",
    picks: "चयन",
    trendingEvents: "ट्रेंडिंग इवेंट्स",
    popularNow: "अभी लोकप्रिय",
    noEventsFound: "कोई इवेंट नहीं मिला",
    tryChangingFilters: "फिल्टर बदलकर देखें",
    removeFromWishlist: "{title} को विशलिस्ट से हटाएं",
    saveToWishlist: "{title} को विशलिस्ट में सेव करें",
    saveEvent: "इवेंट सेव करें",
    viewDetails: "विवरण देखें",
    onwards: "से शुरू",
    chatbotLabel: "SmartEvent चैटबॉट",
    chatbotAssistant: "SmartEvent असिस्टेंट",
    chatbotSubtitle: "इवेंट खोज और सहायता",
    chatbotInitialMessage: "नमस्ते, मैं आपका SmartEvent असिस्टेंट हूं. इवेंट खोजने, बुकिंग देखने या टिकट सहायता के लिए पूछें.",
    chatbotTrending: "ट्रेंडिंग इवेंट्स",
    chatbotBookings: "मेरी बुकिंग्स",
    chatbotMusic: "इस वीकेंड म्यूजिक इवेंट सुझाएं",
    chatbotTickets: "टिकट समस्या में मदद",
    chatbotUnavailable: "अभी असिस्टेंट से संपर्क नहीं हो सका. कृपया फिर कोशिश करें.",
    openRelatedPage: "संबंधित पेज खोलें",
    thinking: "सोच रहा है...",
    askEventsTickets: "इवेंट या टिकट के बारे में पूछें...",
    send: "भेजें",
    openAssistant: "SmartEvent असिस्टेंट खोलें",
    loading: "लोड हो रहा है...",
    myBookings: "मेरी बुकिंग्स",
    bookingsSubtitle: "अपने टिकट, भुगतान कुल और बुकिंग स्थिति देखें.",
    noBookingsYet: "अभी कोई बुकिंग नहीं",
    bookingsEmptyHelp: "बुकिंग बनने के बाद वह यहां स्थिति विवरण के साथ दिखेगी.",
    bookingNumber: "बुकिंग #{id}",
    eventId: "इवेंट ID",
    finalPaid: "अंतिम भुगतान",
    myTickets: "मेरे टिकट",
    ticketsSubtitle: "कन्फर्म टिकट विवरण और QR पास साफ कार्ड लेआउट में देखें.",
    eventTicket: "इवेंट टिकट",
    bookingId: "बुकिंग ID",
    eventDate: "इवेंट तारीख",
    totalPaid: "कुल भुगतान",
    ticketCode: "टिकट कोड",
    qrCode: "QR कोड",
    ticketCancelledInvalid: "इवेंट रद्द है. QR कोड अब मान्य नहीं है.",
    ticketExpiredInvalid: "टिकट समाप्त है. QR कोड अब मान्य नहीं है.",
    downloadTicket: "टिकट डाउनलोड करें",
    myWishlist: "मेरी विशलिस्ट",
    wishlistSubtitle: "इवेंट सेव करें और तैयार होने पर वापस बुकिंग करें.",
    noSavedEvents: "अभी कोई सेव इवेंट नहीं",
    wishlistEmptyHelp: "किसी इवेंट कार्ड पर हार्ट दबाकर उसे बाद के लिए सेव करें.",
    remove: "हटाएं",
    notificationsSubtitle: "बुकिंग, भुगतान, इवेंट और सिस्टम अपडेट एक जगह.",
    markAllRead: "सभी को पढ़ा मार्क करें",
    read: "पढ़ा हुआ",
    unread: "अनपढ़",
    markAsRead: "पढ़ा मार्क करें",
    paymentCancelled: "भुगतान रद्द हो गया. आप फिर कोशिश कर सकते हैं.",
    checkoutLoadFailed: "चेकआउट विवरण लोड नहीं हो सका.",
    paymentFailedRetry: "भुगतान विफल रहा. कृपया फिर कोशिश करें.",
    paymentCouldNotProcess: "भुगतान प्रोसेस नहीं हो सका.",
    paymentSessionMissing: "पेमेंट सेशन नहीं मिला. कृपया फिर से चेकआउट शुरू करें.",
    stripeNotConfigured: "Stripe कॉन्फिगर नहीं है. सिम्युलेटेड चेकआउट इस्तेमाल करें.",
    stripeOpenFailed: "Stripe चेकआउट नहीं खुल सका.",
    loadingCheckout: "चेकआउट लोड हो रहा है...",
    secureCheckout: "सुरक्षित चेकआउट",
    completePayment: "भुगतान पूरा करें",
    bookingTotal: "बुकिंग कुल",
    payableAmount: "भुगतान राशि",
    paymentStatus: "भुगतान स्थिति",
    processing: "प्रोसेस हो रहा है...",
    payWithStripe: "Stripe से भुगतान करें",
    payWithTestCard: "टेस्ट कार्ड से भुगतान करें",
    simulateFailure: "विफलता सिम्युलेट करें",
    backToBookings: "बुकिंग्स पर वापस",
    paymentFailedTitle: "भुगतान विफल",
    paymentSuccessful: "भुगतान सफल",
    paymentFailureCopy: "आपका भुगतान पूरा नहीं हो सका. कृपया चेकआउट फिर करें.",
    paymentSuccessCopy: "आपकी बुकिंग कन्फर्म है और आपका टिकट तैयार हो रहा है.",
    transactionReference: "ट्रांजैक्शन रेफरेंस",
    amount: "राशि",
    viewMyTickets: "मेरे टिकट देखें",
    myProfile: "मेरी प्रोफाइल",
    profileSubtitle: "अपने अकाउंट विवरण संभालें और बुकिंग गतिविधि देखें.",
    smartEventUser: "SmartEvent यूजर",
    editProfile: "प्रोफाइल एडिट करें",
    username: "यूजरनेम",
    email: "ईमेल",
    saving: "सेव हो रहा है...",
    saveProfile: "प्रोफाइल सेव करें",
    profileUpdated: "प्रोफाइल सफलतापूर्वक अपडेट हुई.",
    profileUpdateFailed: "प्रोफाइल अपडेट नहीं हो सकी.",
    activitySummary: "गतिविधि सारांश",
    totalBookings: "कुल बुकिंग्स",
    upcomingEvents: "आने वाले इवेंट्स",
    ticketsBooked: "बुक किए टिकट",
    totalSpent: "कुल खर्च",
    pending: "पेंडिंग",
    closedEvents: "बंद इवेंट्स",
    rewardPoints: "रिवॉर्ड पॉइंट्स",
    rewardPointsHelp: "हर कन्फर्म बुकिंग पर +10, हर रिव्यू पर +5",
    referralSystem: "रेफरल सिस्टम",
    referralSubtitle: "दोस्तों को SmartEvent पर बुलाएं और उनके जुड़ने पर रिवॉर्ड पॉइंट्स पाएं.",
    yourReferralCode: "आपका रेफरल कोड",
    referralCode: "रेफरल कोड",
    successfulReferrals: "सफल रेफरल",
    referralPoints: "रेफरल पॉइंट्स",
    referralHelp: "हर सफल रेफरल पर +{points} रिवॉर्ड पॉइंट्स पाएं.",
    copyReferralCode: "कोड कॉपी करें",
    shareReferralCode: "कोड शेयर करें",
    referralCopied: "रेफरल कोड कॉपी हो गया.",
    referralShareCopied: "रेफरल संदेश कॉपी हो गया.",
    referralCopyFailed: "रेफरल कोड कॉपी नहीं हो सका.",
    referralLoadFailed: "रेफरल विवरण लोड नहीं हो सका.",
    referralShareText: "SmartEvent पर मेरे साथ जुड़ें. मेरा रेफरल कोड इस्तेमाल करें: {code}",
    referralPointsValue: "रेफरल से {points} पॉइंट्स",
    totalEvents: "कुल इवेंट्स",
    activeEvents: "सक्रिय इवेंट्स",
    totalTicketsSold: "कुल बिके टिकट",
    totalRevenue: "कुल रेवेन्यू",
    ongoingEvents: "चल रहे इवेंट्स",
    completedEvents: "पूरे हुए इवेंट्स",
    cancelledEvents: "रद्द इवेंट्स",
    adminOrganizerLogin: "एडमिन / ऑर्गनाइजर लॉगिन",
    enterAdminEmail: "एडमिन ईमेल दर्ज करें",
    enterAdminPassword: "एडमिन पासवर्ड दर्ज करें",
    loginAsAdmin: "एडमिन के रूप में लॉगिन",
    adminOrganizerRequired: "एडमिन/ऑर्गनाइजर एक्सेस आवश्यक है",
    adminLoginFailed: "एडमिन लॉगिन विफल",
    platformAnalytics: "प्लेटफॉर्म एनालिटिक्स",
    analyticsSubtitle: "SmartEvent इनसाइट्स के लिए एडमिन डैशबोर्ड",
    dashboard: "डैशबोर्ड",
    users: "यूजर्स",
    events: "इवेंट्स",
    bookings: "बुकिंग्स",
    loadingAnalytics: "एनालिटिक्स लोड हो रहा है...",
    analyticsLoadFailed: "एनालिटिक्स लोड नहीं हो सका.",
    dailyTicketSales: "दैनिक टिकट बिक्री",
    topRevenueEvents: "टॉप रेवेन्यू इवेंट्स",
    popularEvents: "लोकप्रिय इवेंट्स",
    monthlyBookingTrends: "मासिक बुकिंग ट्रेंड",
    bookingTrendCopy: "बुकिंग ट्रेंड डेटा दैनिक बिक्री व्यू में उपलब्ध है.",
    last7DaysAverage: "पिछले 7 दिनों का औसत",
    bestPerformingDay: "सबसे अच्छा दिन",
    usersOverview: "यूजर्स ओवरव्यू",
    usersOverviewSubtitle: "रजिस्टर्ड यूजर्स और रोल्स संभालें.",
    loadingUsers: "यूजर्स लोड हो रहे हैं...",
    usersLoadFailed: "यूजर्स लोड नहीं हो सके.",
    registeredUsers: "रजिस्टर्ड यूजर्स",
    id: "ID",
    role: "रोल",
    noUsersFound: "कोई यूजर नहीं मिला.",
    eventsOverview: "इवेंट्स ओवरव्यू",
    eventsOverviewSubtitle: "प्लेटफॉर्म इवेंट्स और स्थिति देखें.",
    loadingEvents: "इवेंट्स लोड हो रहे हैं...",
    eventsLoadFailed: "इवेंट्स लोड नहीं हो सके.",
    allEvents: "सभी इवेंट्स",
    title: "शीर्षक",
    status: "स्थिति",
    organizerId: "ऑर्गनाइजर ID",
    price: "कीमत",
    bookingOverview: "बुकिंग ओवरव्यू",
    bookingOverviewSubtitle: "पूरे प्लेटफॉर्म की बुकिंग गतिविधि देखें.",
    loadingBookings: "बुकिंग्स लोड हो रही हैं...",
    bookingsLoadFailed: "बुकिंग्स लोड नहीं हो सकीं.",
    allBookings: "सभी बुकिंग्स",
    userId: "यूजर ID",
    revenue: "रेवेन्यू",
    noBookingsFound: "कोई बुकिंग नहीं मिली.",
    adminDashboard: "एडमिन डैशबोर्ड",
    organizerDashboard: "ऑर्गनाइजर डैशबोर्ड",
    admin: "एडमिन",
    organizer: "ऑर्गनाइजर",
    platformAnalyticsLink: "प्लेटफॉर्म एनालिटिक्स",
    eventInsights: "इवेंट इनसाइट्स",
    closeInsights: "इनसाइट्स बंद करें",
    loadingInsights: "इनसाइट्स लोड हो रहे हैं...",
    insightsLoadFailed: "इवेंट इनसाइट्स लोड नहीं हो सके",
    ticketsSold: "बिके टिकट",
    remainingTickets: "बचे टिकट",
    bookingCount: "बुकिंग गिनती",
    salesProgress: "सेल्स प्रोग्रेस",
    ticketsSoldProgress: "{sold} / {total} टिकट बिके",
    addEvent: "इवेंट जोड़ें",
    updateEvent: "इवेंट अपडेट करें",
    cancelEdit: "एडिट रद्द करें",
    description: "विवरण",
    selectCategory: "श्रेणी चुनें",
    comedy: "कॉमेडी",
    music: "म्यूजिक",
    tech: "टेक",
    business: "बिजनेस",
    sports: "स्पोर्ट्स",
    workshop: "वर्कशॉप",
    selectedImagePreview: "चुनी गई इमेज प्रीव्यू:",
    selectedEventBannerPreview: "चुने गए इवेंट बैनर का प्रीव्यू",
    fillAllEventFields: "कृपया इवेंट इमेज सहित सभी फील्ड भरें.",
    eventUpdated: "इवेंट अपडेट हुआ",
    eventAdded: "इवेंट जोड़ा गया",
    eventAddFailed: "इवेंट जोड़ना विफल रहा",
    eventCancelledNotify: "इवेंट रद्द हुआ और यूजर्स को सूचना भेजी गई",
    cancelFailed: "रद्द करना विफल रहा",
    enterAnnouncementFirst: "पहले घोषणा संदेश दर्ज करें",
    eventUpdatePosted: "इवेंट अपडेट पोस्ट हुआ",
    eventUpdatePostFailed: "इवेंट अपडेट पोस्ट नहीं हो सका",
    yourEvents: "आपके इवेंट्स",
    thumbnail: "थंबनेल",
    viewInsights: "इनसाइट्स देखें",
    edit: "एडिट",
    cancelEvent: "इवेंट रद्द करें",
    postLiveUpdate: "अटेंडीज के लिए लाइव अपडेट पोस्ट करें...",
    important: "महत्वपूर्ण",
    postUpdate: "अपडेट पोस्ट करें",
    statusConfirmed: "कन्फर्म",
    statusCancelled: "रद्द",
    statusExpired: "समाप्त",
    statusPending: "पेंडिंग",
  },
};

export const LanguageContext = createContext(null);
